[project]
name = "simple-plugin-demo"
version = "0.1.0"
description = "Demo using the pytest-pydantic-schema-sync plugin"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "pydantic"
]

[tool.pytest.ini_options]
# These are the defaults
# pydantic_schema_sync = '{"schema_location":"package_root","schema_dir":"schemas","repo_flatten":false}'

[tool.pdm.dev-dependencies]
test = [
  "pytest-pydantic-schema-sync",
  "inline-snapshot>=0.12.1"
]

[tool.uv.sources]
pytest-pydantic-schema-sync = {workspace = true}
