[project]
name = "simple-plugin-demo"
version = "0.1.0"
description = "Demo using the pytest-pydantic-schema-sync plugin"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "pydantic"
]

[tool.pdm.dev-dependencies]
test = [
  "pytest-pydantic-schema-sync",
  "inline-snapshot>=0.12.1"
]

[tool.pytest.ini_options]
# Override the use of aliases in the schema
pydantic_schema_sync = {mjs_kwargs = {by_alias = false}}

[tool.uv.sources]
pytest-pydantic-schema-sync = {workspace = true}
