[project]
name = "demo-test-package"
version = "0.1.0"
description = "Demo using the pytest plugin for pydantic-schema-sync"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "pytest-pydantic-schema-sync",
  "pydantic"
]

[tool.uv.sources]
pytest-pydantic-schema-sync = {workspace = true}
