[project]
name = "demo-test-package"
version = "0.1.0"
description = "Demo using the pytest plugin for pydantic-schema-sync"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "pydantic"
]

[tool.pdm.dev-dependencies]
test = [
  "pytest-pydantic-schema-sync @ file:///${PROJECT_ROOT}/../pytest-pydantic-schema-sync",
  "inline-snapshot>=0.12.1"
]

[tool.uv.sources]
pytest-pydantic-schema-sync = {workspace = true}
